version: '3.0'

services:
  nestjs-api:
    container_name: nestjs-api
    image: ghcr.io/duyhoan1710/nestjs-api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - .data/mysql:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
