name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.0.0'
      - run: npm i
      - run: npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - npm run test
  #   needs: [lint]

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - npm run build
  #   needs: [lint, test]

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - npm run build
  #   needs: [lint, test, build]
